### ISSUE TITLE
Errror in context

### ISSUE THREAD

**Issue by beachtom** [Accord-Project/aec3po#102]
Hi,

Since the last update JSON-LD processing throwing errors about the context.

it does not like the use of @base in term definitions

jsonld.SyntaxError: Invalid JSON-LD syntax; a term definition must not contain @base

**Comment by AmnaKRDB** [comment]
sorted out via https://github.com/Accord-Project/aec3po/commit/fe9f75a40d631dd3057dbe4601ad81833891b934

**Comment by beachtom** [comment]
still happening I'm afraid

**Comment by AmnaKRDB** [comment]
Previously, there was a syntax error failing the run. I thought this was the source of the issue that prevents the correct generation of the context. Now, given that the error has been corrected, I am not sure about the persistent error in the context.

**Comment by maximelefrancois86** [comment]
In #84 it was requested to add a `@base` keyword at the level of individual items, and apparently that isn't compliant with JSON-LD.
Maybe they shall be deleted at lines 26-27

**Comment by maximelefrancois86** [comment]
What about now with latest commit ?

**Comment by beachtom** [comment]
yeah it works fine now. Sorry about that - all sorted now though
