### ISSUE TITLE
RASEDecomposedStatement

### ISSUE THREAD

**Issue by beachtom** [Accord-Project/aec3po#66]
RASEDecomposedStatement does not seem to be required - and can be removed

**Comment by maximelefrancois86** [comment]
Apparently commit https://github.com/Accord-Project/aec3po/commit/419d3863e433f264eb3a3ddedd916ab348edb58d commented out the class RASEDecomposedStatement.

This commit should have referred to this issue, or a comment in this issue should refer to that commit.

At least, the job should be done completely, commenting out lines 41, 57, 73, 89, in this same file.

**Comment by beachtom** [comment]
Would suggest completely removing this I do not think it is needed

**Comment by maximelefrancois86** [comment]
If the PR is fine with you, please approve it, we'll merge, and this will close this issue automatically
