### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by beachtom** [Accord-Project/aec3po#72]
Hi,

In my YAML file I find I need to refer to SI units using a URL.

Does using https://github.com/HajoRijgersberg/OM make sense or do you have an alternative suggestions?

**Comment by maximelefrancois86** [comment]
unit: prefix is added to the jsonld context in [ce186e2](https://github.com/Accord-Project/aec3po/commit/ce186e265da85a08a8b685224010c930c258f553)
