### ISSUE TITLE
Context corrections

### ISSUE THREAD

**Issue by beachtom** [Accord-Project/aec3po#84]
Hi,

We need to make a few changes to the context. There are a few properties we need to flag as a URI type:

An example is hasComparator we need this for this property:

  $id: aec3po:hasComparator
  $type: $id
  $context:
    $base: https://w3id.org/lbd/aec3po/

Other properties that need to change are:

hasUnit

which needs

  $id: qudt:hasUnit
  $type: $id
  $context:
    $base: http://qudt.org/vocab/unit/

**Comment by beachtom** [comment]
Also we need:

executes

which needs

$id: fno:executes
$type: $id
$context:
$base: https://data.accordproject.eu/functions

**Comment by maximelefrancois86** [comment]
commit [ce186e2](https://github.com/Accord-Project/aec3po/commit/ce186e265da85a08a8b685224010c930c258f553)

adds fno:executes and qudt:hasUnit in the context, and generates @type: @id whenever a aec3po entity is an ObjectProperty
